// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"LinearMotionBattleSystem_Core","status":true,"description":"Tweek the battle system to LMBS battle system","parameters":{"===Battle Value Settings===":"","Battle Field Width":"816","Battle Field Ground Y":"500","Maximum Fall Speed":"20","Animation Speed":"10","Damage Popup Offset X":"0","Damage Popup Offset Y":"-40","Turn Length":"60","Jump Power":"15","Enemy X Start":"520","Battle End Wait Time":"200","Auto Guard Time After Guard":"15","===System Settings===":"","Enable Default":"true","Debug Mode":"false","Default Facing":"false","Double Tap Time":"15","Can Move Through Ally":"true","Can Move Through Enemy":"false","Can Dash Through Ally":"true","Can Dash Through Enemy":"true","Fix Character Size":"true","Skill Set Left Right Act Same":"true","Delay for jump":"4","===Menu Settings===":"","Skill Set Name":"Config","Battle Skill Command Name":"Skill/Magic","Battle Item Command Name":"Item","Battle Skill Icon":"76","Battle Item Icon":"176","===Camera Settings===":"","Max Camera Zoom":"2","Min Camera Zoom":"0.90","Camera Left Margin":"100","Camera Right Margin":"30"}}
];
